{{- if .Values.mcp.http.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubegram-operator.fullname" . }}
  labels:
    {{- include "kubegram-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.mcp.http.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "kubegram-operator.selectorLabels" . | nindent 4 }}
{{- end }}
